name: material_3_demo
description:
  A Flutter project showcasing supported Material 3 components, typography, color system and elevation.
  Supports different light/dark mode, color seed, and comparison to Material 2.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.3.0
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  web_startup_analyzer:
    git: https://github.com/vitcon-lonton/web_startup_analyzer.git
  # iconify_flutter: ^0.0.5
  standard_ui_kit:
    path: packages/standard_ui_kit
  diversity_avatars:
    path: packages/diversity_avatars
  bulk_icons:
    path: packages/bulk_icons

dev_dependencies:
  analysis_defaults:
    git: https://github.com/vitcon-lonton/analysis_defaults.git
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
