name: diversity_avatars
description: DiversityAvatars Flutter package
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/src/
  assets:
    outputs:
      class_name: DiversityAvatars
      package_parameter_enabled: true

flutter:
  assets:
    - assets/